{% set version = '3.0' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rmeta
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rmeta_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rmeta/rmeta_{{ version }}.tar.gz
  sha256: b9f9d405935cffcd7a5697ff13b033f9725de45f4dc7b059fd68a7536eb76b6e

build:
  noarch: generic
  number: 1006
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('rmeta')"           # [not win]
    - "\"%R%\" -e \"library('rmeta')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=rmeta
  license: GPL-2.0-only
  summary: Functions for simple fixed and random effects meta-analysis for two-sample comparisons
    and cumulative meta-analyses. Draws standard summary plots, funnel plots, and computes
    summaries and tests for association and heterogeneity.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
