appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: CrBvCBvmdTb0WwCWlGwrY8MiJPHMnEs12BB85Hqg/Zjg5BPUsNwdySVSlEdJAonT/uBMAV17nss6pn8qbw7pfxHMuJbJ+zH3eNcU12R4h74ND+teJIvWg2t7+E49xwJTv+AakInkN00C/TzfSxwWgnhKNs5foEsczdyY0ahvZkK7PempwlMM48jzpHnDdGyzZLSXqwtFcZtAZa82rHeSJCGqelcGlgtH/WwGfLv4iQl+vv4X/JqPjsZ3fBCbGfpBMmpumQr3xlMg+0fGmWRphhPJ4XYPmGA41MLd3fE/tUud72RfCtwWT5QWCN42dibpazi9DL+D5mYewWkehDBqGPCwBoGJ0K4TJ4is72qfcfB+/k7hm94v3jO6qwUPdIxmcW0nMr7cneAaJmAuipMfwJhjBROqkg3W1+WsYIlDdzjV9A7JunqcsWyXaWVMkMjqY86eyetffNspbrQXYDY9LbzwduCuPlydWKhKycC8JuM9BcYfe4efCITAiXke51/lvRvOBtM8kgKJCbMjCkhTIIz2UHPtuxO5r0WuVlBuUkOIn3DXFOEMHwMXYVoXpZszs6TcXuGHHep/DFI/tjybw5OhasSKE7o3HimuHc8Em1WGysInuOWf7GgKrk+A4Gp07R74W0//FD9MG+vtFv1JGRwfBnJCRwtC8ao8eToOWxo=
